#!/usr/bin/env python
from povimage import POVConvert

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
            description="Convert image to POV coordinates")

    parser.add_argument('--innerRadius', '-r', dest='innerRadius', type=float,
            default=0.2, help="Inner radius (0.0-1.0, default: 0.2)")

    parser.add_argument('--input', '-i', dest='src',
            type=argparse.FileType('r'), required=True)

    parser.add_argument('--output','-o', dest='dst',
            type=argparse.FileType('w'), required=True)

    args = parser.parse_args()

    converter = POVConvert(args.src, args.innerRadius)
    converter.convert()
    converter.save(args.dst)

    args.dst.close()

